
import { Question } from '../types';

export const ALL_QUESTIONS: Question[] = [
  // --- Requisitos Gerais ---
  {
    id: 'RG1.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'O relatório IFRS S1 está em conformidade com as Demonstrações Financeiras (DFs), sendo ambos referentes à mesma entidade reportadora e às mesmas organizações subsidiárias?',
    type: 'boolean',
    evidence_prompt: 'Confirme o nome da entidade reportadora e as DFs relacionadas. Forneça evidências (ex: trecho do relatório) que comprovem a consistência.',
    reference: 'IFRS S1, §20',
    reference_text: "20 An entity's sustainability-related financial disclosures shall be for the same reporting entity as the related financial statements (see paragraph B38).",
    priority: 'moderate',
  },
  {
    id: 'RG1.2',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'O relatório descreve a entidade reportadora, informando sobre as atividades realizadas e empresas subsidiárias contempladas?',
    type: 'boolean',
    evidence_prompt: 'Indique onde esta descrição pode ser encontrada e anexe trechos relevantes que demonstrem a abrangência da descrição.',
    reference: 'IFRS S1, §13',
    reference_text: "13 Fair presentation requires disclosure of relevant information about sustainability-related risks and opportunities that could reasonably be expected to affect the entity's prospects, and their faithful representation in accordance with the principles set out in this Standard. To achieve faithful representation, an entity shall provide a complete, neutral and accurate depiction of those sustainability-related risks and opportunities.",
    priority: 'moderate',
  },
  {
    id: 'RG2.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'A entidade fornece informações de forma a permitir que os usuários compreendam as conexões entre os vários riscos e oportunidades, e entre as divulgações de sustentabilidade e os outros relatórios financeiros?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a entidade garante a conectividade das informações (ex: referências cruzadas, narrativa integrada) e anexe exemplos do relatório.',
    reference: 'IFRS S1, §21',
    reference_text: "21 An entity shall provide information in a manner that enables users of general purpose financial reports to understand the following types of connections:\n(a) the connections between the items to which the information relates—such as connections between various sustainability-related risks and opportunities that could reasonably be expected to affect the entity's prospects; and\n(b) the connections between disclosures provided by the entity:\n(i) within its sustainability-related financial disclosures—such as connections between disclosures on governance, strategy, risk management and metrics and targets; and\n(ii) across its sustainability-related financial disclosures and other general purpose financial reports published by the entity —such as its related financial statements (see paragraphs B39–B44).",
    priority: 'moderate',
  },
  {
    id: 'RG3.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'A entidade identifica as demonstrações financeiras a que as divulgações de sustentabilidade se referem?',
    type: 'boolean',
    evidence_prompt: 'Forneça a identificação exata das demonstrações financeiras referenciadas, conforme divulgado no relatório.',
    reference: 'IFRS S1, §22',
    reference_text: "22 An entity shall identify the financial statements to which the sustainability-related financial disclosures relate.",
    priority: 'moderate',
  },
  {
    id: 'RG4.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'Os dados e premissas utilizados nas divulgações de sustentabilidade são consistentes com os utilizados nas demonstrações financeiras, na medida do possível?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a consistência é mantida ou explique e anexe evidências de quaisquer inconsistências relevantes.',
    reference: 'IFRS S1, §23',
    reference_text: "23 Data and assumptions used in preparing the sustainability-related financial disclosures shall be consistent to the extent possible considering the requirements of IFRS Accounting Standards or other applicable GAAP— with the corresponding data and assumptions used in preparing the related financial statements (see paragraph B42).",
    priority: 'moderate',
  },
  {
    id: 'RG5.1',
    topic: 'Requisitos Gerais',
    subtopic: 'Divulgação Integrada',
    text: 'A unidade monetária utilizada no reporte de Sustentabilidade é a mesma do reporte financeiro?',
    type: 'boolean',
    evidence_prompt: 'Confirme a moeda de apresentação utilizada e indique a página do relatório onde essa informação pode ser encontrada.',
    reference: 'IFRS S1, §24',
    reference_text: "24 When currency is specified as the unit of measure in the sustainability-related financial disclosures, the entity shall use the presentation currency of its related financial statements.",
    priority: 'moderate',
  },

  // --- Governança ---
  {
    id: 'GV2.1',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'Qual órgão de governança ou indivíduo é responsável pela supervisão dos SRROs?',
    type: 'single_choice',
    options: ['Conselho de Administração', 'Comitê de Sustentabilidade', 'Comitê de Auditoria', 'Outro'],
    evidence_prompt: 'Forneça o trecho do estatuto, regimento interno ou ata de reunião que designa esta responsabilidade.',
    reference: 'IFRS S1, §27(a)',
    reference_text: "27 To achieve this objective, an entity shall disclose information about:\n(a) the governance body(s) (which can include a board, committee or equivalent body charged with governance) or individual(s) responsible for oversight of sustainability-related risks and opportunities. Specifically, the entity shall identify that body(s) or individual(s) and disclose information about:\n(i) how responsibilities for sustainability-related risks and opportunities are reflected in the terms of reference, mandates, role descriptions and other related policies applicable to that body(s) or individual(s);\n(ii) how the body(s) or individual(s) determines whether appropriate skills and competencies are available or will be developed to oversee strategies designed to respond to sustainability-related risks and opportunities;\n(iii) how and how often the body(s) or individual(s) is informed about sustainability-related risks and opportunities;\n(iv) how the body(s) or individual(s) takes into account sustainability-related risks and opportunities when overseeing the entity's strategy, its decisions on major transactions and its risk management processes and related policies, including whether the body(s) or individual(s) has considered trade-offs associated with those risks and opportunities; and\n(v) how the body(s) or individual(s) oversees the setting of targets related to sustainability-related risks and opportunities, and monitors progress towards those targets (see paragraph 51), including whether and how related performance metrics are included in remuneration policies.",
    priority: 'moderate',
  },
  {
    id: 'GV2.2',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'A instituição informa como as habilidades e competências em relação aos SRROs são avaliadas ou desenvolvidas no corpo de governança?',
    type: 'boolean',
    evidence_prompt: 'Descreva o processo de avaliação de competências e/ou o plano de desenvolvimento. Anexe atas ou relatórios relevantes.',
    reference: 'IFRS S1, §27(a)(ii)',
    reference_text: "(ii) how the body(s) or individual(s) determines whether appropriate skills and competencies are available or will be developed to oversee strategies designed to respond to sustainability-related risks and opportunities;",
    priority: 'moderate',
  },
  {
    id: 'GV2.3',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'A instituição divulga quando e com qual frequência os membros do corpo de governança são informados sobre os SRROs?',
    type: 'boolean',
    evidence_prompt: 'Especifique a frequência e os momentos (ex: reuniões trimestrais do conselho) e anexe o calendário de reuniões ou trecho da ata.',
    reference: 'IFRS S1, §27(a)(iii)',
    reference_text: "(iii) how and how often the body(s) or individual(s) is informed about sustainability-related risks and opportunities;",
    priority: 'moderate',
  },
  {
    id: 'GV2.4',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'É divulgado como o corpo de governança avalia a definição de metas relacionadas aos SRROs e monitora seu progresso?',
    type: 'boolean',
    evidence_prompt: 'Descreva o processo de avaliação e monitoramento de metas pela governança e anexe evidências (ex: painéis de controle, atas).',
    reference: 'IFRS S1, §27(a)(v)',
    reference_text: "(v) how the body(s) or individual(s) oversees the setting of targets related to sustainability-related risks and opportunities, and monitors progress towards those targets (see paragraph 51), including whether and how related performance metrics are included in remuneration policies.",
    priority: 'moderate',
  },
  {
    id: 'GV2.5',
    topic: 'Governança',
    subtopic: 'Supervisão do Órgão de Governança',
    text: 'A entidade divulga como considerações climáticas são fatoradas na remuneração executiva?',
    type: 'boolean',
    evidence_prompt: 'Descreva como as considerações climáticas são incorporadas na remuneração e anexe a política de remuneração ou o trecho do relatório.',
    reference: 'IFRS S2, §29(g)',
    reference_text: "29(g) remuneration—the entity shall disclose:\n(i) a description of whether and how climate-related considerations are factored into executive remuneration (see also paragraph 6(a)(v)); and\n(ii) the percentage of executive management remuneration recognised in the current period that is linked to climate- related considerations.",
    priority: 'moderate',
  },
  {
    id: 'GV3.1',
    topic: 'Governança',
    subtopic: 'Papel da Gestão',
    text: 'A entidade divulga o papel da gestão nos processos de governança, incluindo se a função é delegada a um cargo específico ou a um comitê?',
    type: 'boolean',
    evidence_prompt: 'Descreva o papel da gestão, indicando o cargo ou comitê ao qual as responsabilidades foram delegadas. Anexe a política de governança ou organograma.',
    reference: 'IFRS S1, §27(b)(i)',
    reference_text: "(b) management's role in the governance processes, controls and procedures used to monitor, manage and oversee sustainability-related risks and opportunities, including information about:\n(i) whether the role is delegated to a specific management-level position or management-level committee and how oversight is exercised over that position or committee;",
    priority: 'moderate',
  },
  {
    id: 'GV3.2',
    topic: 'Governança',
    subtopic: 'Papel da Gestão',
    text: 'A entidade informa como é feita a supervisão a esse responsável?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a supervisão é exercida sobre o cargo ou comitê responsável. Anexe atas de reunião ou relatórios de acompanhamento.',
    reference: 'IFRS S1, §27(b)(i)',
    reference_text: "(b) management's role in the governance processes, controls and procedures used to monitor, manage and oversee sustainability-related risks and opportunities, including information about:\n(i) whether the role is delegated to a specific management-level position or management-level committee and how oversight is exercised over that position or committee;",
    priority: 'moderate',
  },

  // --- Estratégia ---
  {
    id: 'ES2.1',
    topic: 'Estratégia',
    subtopic: 'Identificação de Riscos e Oportunidades',
    text: 'Descrição dos SRROs que podem afetar suas perspectivas, especificando os horizontes temporais (curto, médio e longo prazo)?',
    type: 'text_block',
    evidence_prompt: 'Liste os principais SRROs e os horizontes de tempo associados. Explique como a entidade define cada horizonte temporal.',
    reference: 'IFRS S1, §30-31',
    reference_text: "30 An entity shall disclose information that enables users of general purpose financial reports to understand the sustainability-related risks and opportunities that could reasonably be expected to affect the entity's prospects. Specifically, the entity shall:\n(a) describe sustainability-related risks and opportunities that could reasonably be expected to affect the entity's prospects;\n(b) specify the time horizons—short, medium or long term—over which the effects of each of those sustainability-related risks and opportunities could reasonably be expected to occur; and\n(c) explain how the entity defines 'short term', 'medium term' and 'long term' and how these definitions are linked to the planning horizons used by the entity for strategic decision-making.\n---\n31 Short-, medium- and long- term time horizons can vary between entities and depend on many factors, including industry-specific characteristics, such as cash flow, investment and business cycles, the planning horizons typically used in an entity's industry for strategic decision-making and capital allocation plans, and the time horizons over which users of general purpose financial reports conduct their assessments of entities in that industry.",
    priority: 'moderate',
  },
  {
    id: 'ES3.1',
    topic: 'Estratégia',
    subtopic: 'Impacto no Modelo de Negócios',
    text: "Como a entidade descreve os efeitos atuais e previstos dos SRROs em seu modelo de negócios e cadeia de valor?",
    type: 'text_block',
    evidence_prompt: 'Forneça a descrição dos efeitos atuais e previstos dos SRROs no modelo de negócios e na cadeia de valor da entidade.',
    reference: 'IFRS S1, §32(a)',
    reference_text: "32 An entity shall disclose information that enables users of general purpose financial reports to understand the current and anticipated effects of sustainability-related risks and opportunities on the entity's business model and value chain. Specifically, the entity shall disclose:\n(a) a description of the current and anticipated effects of sustainability- related risks and opportunities on the entity's business model and value chain; and\n(b) a description of where in the entity's business model and value chain sustainability-related risks and opportunities are concentrated (for example, geographical areas, facilities and types of assets).",
    priority: 'moderate',
  },
  {
    id: 'ES3.2',
    topic: 'Estratégia',
    subtopic: 'Impacto no Modelo de Negócios',
    text: "Onde se concentram os SRROs no modelo de negócios e na cadeia de valor da entidade?",
    type: 'text_block',
    evidence_prompt: "Descreva onde, na cadeia de valor, os SRROs estão concentrados (por exemplo, áreas geográficas, instalações, tipos de ativos) e anexe o mapa da cadeia de valor, se houver.",
    reference: 'IFRS S1, §32(b)',
    reference_text: "32 An entity shall disclose information that enables users of general purpose financial reports to understand the current and anticipated effects of sustainability-related risks and opportunities on the entity's business model and value chain. Specifically, the entity shall disclose:\n(a) a description of the current and anticipated effects of sustainability- related risks and opportunities on the entity's business model and value chain; and\n(b) a description of where in the entity's business model and value chain sustainability-related risks and opportunities are concentrated (for example, geographical areas, facilities and types of assets).",
    priority: 'moderate',
  },
  {
    id: 'ES4.1',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Apresenta como a entidade respondeu e planeja responder aos SRROs na sua estratégia e tomada de decisão, incluindo o progresso sobre planos de períodos anteriores?',
    type: 'text_block',
    evidence_prompt: 'Descreva a resposta estratégica, os planos, os trade-offs considerados e o progresso (qualitativo e quantitativo) em relação a planos passados.',
    reference: 'IFRS S1, §33',
    reference_text: "33 An entity shall disclose information that enables users of general purpose financial reports to understand the effects of sustainability-related risks and opportunities on its strategy and decision-making. Specifically, the entity shall disclose information about:\n(a) how the entity has responded to, and plans to respond to, sustainability-related risks and opportunities in its strategy and decision-making;\n(b) the progress against plans the entity has disclosed in previous reporting periods, including quantitative and qualitative information; and\n(c) trade-offs between sustainability-related risks and opportunities that the entity considered (for example, in making a decision on the location of new operations, an entity might have considered the environmental impacts of those operations and the employment opportunities they would create in a community).",
    priority: 'moderate',
  },
  {
    id: 'ES5.1',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'A entidade divulga os efeitos atuais e antecipados dos SRROs em sua posição financeira, desempenho e fluxos de caixa?',
    type: 'boolean',
    evidence_prompt: 'Descreva os efeitos financeiros atuais e previstos, fornecendo informações quantitativas e qualitativas. Anexe os trechos relevantes das demonstrações financeiras e do relatório.',
    reference: 'IFRS S1, §34',
    reference_text: "34 An entity shall disclose information that enables users of general purpose financial reports to understand:\n(a) the effects of sustainability-related risks and opportunities on the entity's financial position, financial performance and cash flows for the reporting period (current financial effects); and\n(b) the anticipated effects of sustainability-related risks and opportunities on the entity's financial position, financial performance and cash flows over the short, medium and long term, taking into consideration how sustainability-related risks and opportunities are included in the entity's financial planning (anticipated financial effects).",
    priority: 'moderate',
  },
  {
    id: 'ES5.2',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Apresenta como esses SRROs e as estratégias para gerenciá-los são levados em consideração no planejamento financeiro da empresa?',
    type: 'boolean',
    evidence_prompt: 'Descreva como os SRROs são integrados no planejamento financeiro. Anexe o plano de investimentos e alocação de capital relacionado.',
    reference: 'IFRS S1, §35',
    reference_text: "35 Specifically, an entity shall disclose quantitative and qualitative information about:\n(a) how sustainability-related risks and opportunities have affected its financial position, financial performance and cash flows for the reporting period;\n(b) the sustainability-related risks and opportunities identified in paragraph 35(a) for which there is a significant risk of a material adjustment within the next annual reporting period to the carrying amounts of assets and liabilities reported in the related financial statements;\n(c) how the entity expects its financial position to change over the short, medium and long term, given its strategy to manage sustainability- related risks and opportunities, taking into consideration:\n(i) its investment and disposal plans (for example, plans for capital expenditure, major acquisitions and divestments, joint ventures, business transformation, innovation, new business areas, and asset retirements), including plans the entity is not contractually committed to; and\n(ii) its planned sources of funding to implement its strategy; and\n(d) how the entity expects its financial performance and cash flows to change over the short, medium and long term, given its strategy to manage sustainability-related risks and opportunities.",
    priority: 'moderate',
  },
  {
    id: 'ES5.3',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'A entidade conseguiu mensurar os efeitos financeiros antecipados dos SRROs?',
    type: 'boolean',
    evidence_prompt: 'Anexe a seção do relatório que contém os dados quantitativos sobre os efeitos financeiros antecipados.',
    reference: 'IFRS S1, §38',
    reference_text: "38 An entity need not provide quantitative information about the current or anticipated financial effects of a sustainability-related risk or opportunity if the entity determines that:\n(a) those effects are not separately identifiable; or\n(b) the level of measurement uncertainty involved in estimating those effects is so high that the resulting quantitative information would not be useful (see paragraphs 77-82).",
    priority: 'moderate',
  },
  {
    id: 'ES5.4',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Em caso de não mensuração, a entidade explica o porquê da ausência da informação quantitativa?',
    type: 'boolean',
    evidence_prompt: 'Anexe a justificativa para a não divulgação (ex: impossível identificar separadamente, incerteza elevada, falta de recursos).',
    reference: 'IFRS S1, §40(a)',
    reference_text: "40 If an entity determines that it need not provide quantitative information about the current or anticipated financial effects of a sustainability-related risk or opportunity applying the criteria set out in paragraphs 38-39, the entity shall:\n(a) explain why it has not provided quantitative information;",
    priority: 'moderate',
  },
  {
    id: 'ES5.5',
    topic: 'Estratégia',
    subtopic: 'Planejamento e Resposta Estratégica',
    text: 'Mesmo não divulgando dados quantitativos, a entidade informa sobre os dados qualitativos dos efeitos antecipados?',
    type: 'boolean',
    evidence_prompt: 'Indique onde as informações qualitativas sobre os efeitos antecipados são divulgadas e anexe o trecho correspondente.',
    reference: 'IFRS S1, §40(b)',
    reference_text: "40 If an entity determines that it need not provide quantitative information...the entity shall:\n(b) provide qualitative information about those financial effects, including identifying line items, totals and subtotals within the related financial statements that are likely to be affected, or have been affected, by that sustainability-related risk or opportunity; and",
    priority: 'moderate',
  },
  {
    id: 'ES6.1',
    topic: 'Estratégia',
    subtopic: 'Análise de Resiliência',
    text: 'Como a empresa divulga informações qualitativas e quantitativas sobre a resiliência de sua estratégia e modelo de negócios frente aos riscos relacionados à sustentabilidade?',
    type: 'text_block',
    evidence_prompt: 'Forneça a avaliação (qualitativa e/ou quantitativa) da resiliência da estratégia, incluindo a capacidade de se ajustar a incertezas. Anexe o estudo de resiliência.',
    reference: 'IFRS S1, §41',
    reference_text: "41 An entity shall disclose information that enables users of general purpose financial reports to understand its capacity to adjust to the uncertainties arising from sustainability-related risks. An entity shall disclose a qualitative and, if applicable, quantitative assessment of the resilience of its strategy and business model in relation to its sustainability-related risks, including information about how the assessment was carried out and its time horizon. When providing quantitative information, an entity may disclose a single amount or a range.",
    priority: 'moderate',
  },
  {
    id: 'ES6.2',
    topic: 'Estratégia',
    subtopic: 'Análise de Resiliência',
    text: 'A entidade utiliza análise de cenários climáticos para avaliar sua resiliência climática?',
    type: 'boolean',
    evidence_prompt: 'Descreva a avaliação de resiliência climática, incluindo informações sobre os cenários utilizados, premissas e como a análise foi realizada. Anexe o relatório de análise de cenários.',
    reference: 'IFRS S2, §22',
    reference_text: "22 An entity shall disclose information that enables users of general purpose financial reports to understand the resilience of the entity's strategy and business model to climate-related changes, developments and uncertainties, taking into consideration the entity's identified climate-related risks and opportunities. The entity shall use climate-related scenario analysis to assess its climate resilience using an approach that is commensurate with the entity's circumstances (see paragraphs B1-B18). In providing quantitative information, the entity may disclose a single amount or a range. Specifically, the entity shall disclose:\n(a) the entity's assessment of its climate resilience as at the reporting date, which shall enable users of general purpose financial reports to understand: [...]\n(b) how and when the climate-related scenario analysis was carried out, including: [...]",
    priority: 'moderate',
  },
  {
    id: 'ES7.1',
    topic: 'Estratégia',
    subtopic: 'Gestão de Riscos Climáticos',
    text: 'Tópico(s) coberto(s) pela divulgação sobre o gerenciamento integrado de riscos (ou seja, quando fala da gestão de riscos climáticos, quais temas estão cobertos).',
    type: 'text_block',
    evidence_prompt: 'Liste os temas climáticos cobertos e anexe a seção do relatório que descreve a gestão integrada de riscos.',
    reference: 'IFRS S2.26',
    reference_text: "25 To achieve this objective, an entity shall disclose information about:\n(a) the processes and related policies the entity uses to identify, assess, prioritise and monitor climate-related risks, including information about: [...]\n(b) the processes the entity uses to identify, assess, prioritise and monitor climate-related opportunities, including information about whether and how the entity uses climate-related scenario analysis to inform its identification of climate-related opportunities; and\n(c) the extent to which, and how, the processes for identifying, assessing, prioritising and monitoring climate-related risks and opportunities are integrated into and inform the entity's overall risk management process.\n---\n26 In preparing disclosures to fulfil the requirements in paragraph 25, an entity shall avoid unnecessary duplication in accordance with IFRS S1 (see paragraph B42(b) of IFRS S1). For example, although an entity shall provide the information required by paragraph 25, if oversight of sustainability- related risks and opportunities is managed on an integrated basis, the entity would avoid duplication by providing integrated risk management disclosures instead of separate disclosures for each sustainability-related risk and opportunity.",
    priority: 'moderate',
  },

  // --- Gestão de Riscos ---
  {
    id: 'GR1.1',
    topic: 'Gestão de Riscos',
    subtopic: 'Processos de Gestão de Risco',
    text: 'A entidade divulga as políticas e os processos que utiliza para identificar, avaliar, priorizar e monitorar SRROs?',
    type: 'boolean',
    evidence_prompt: 'Anexe a política de gestão de riscos e oportunidades de sustentabilidade ou o manual de procedimentos.',
    reference: 'IFRS S1, §43-44',
    reference_text: "43 The objective of sustainability-related financial disclosures on risk management is to enable users of general purpose financial reports:\n(a) to understand an entity's processes to identify, assess, prioritise and monitor sustainability-related risks and opportunities, including whether and how those processes are integrated into and inform the entity's overall risk management process; and\n(b) to assess the entity's overall risk profile and its overall risk management process.\n---\n44 To achieve this objective, an entity shall disclose information about:\n(a) the processes and related policies the entity uses to identify, assess, prioritise and monitor sustainability-related risks, including information about: [...]\n(b) the processes the entity uses to identify, assess, prioritise and monitor sustainability-related opportunities; and\n(c) the extent to which, and how, the processes for identifying, assessing, prioritising and monitoring sustainability-related risks and opportunities are integrated into and inform the entity's overall risk management process.",
    priority: 'moderate',
  },
  {
    id: 'GR1.2',
    topic: 'Gestão de Riscos',
    subtopic: 'Integração e Análise',
    text: 'Os processos de gestão de SRROs estão integrados ao processo geral de gestão de riscos da entidade?',
    type: 'boolean',
    evidence_prompt: 'Descreva como os processos estão integrados e como eles informam a gestão de risco geral. Anexe o fluxograma do processo integrado.',
    reference: 'IFRS S1, §44(c)',
    reference_text: "44 To achieve this objective, an entity shall disclose information about: [...]\n(c) the extent to which, and how, the processes for identifying, assessing, prioritising and monitoring sustainability-related risks and opportunities are integrated into and inform the entity's overall risk management process.",
    priority: 'moderate',
  },
  {
    id: 'GR1.3',
    topic: 'Gestão de Riscos',
    subtopic: 'Integração e Análise',
    text: 'A entidade utiliza análise de cenários climáticos para informar a identificação de riscos relacionados ao clima?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a análise de cenários é usada para identificar riscos climáticos e anexe a seção relevante do estudo.',
    reference: 'IFRS S2, §25(a)(ii)',
    reference_text: "25 To achieve this objective, an entity shall disclose information about:\n(a) the processes and related policies the entity uses to identify, assess, prioritise and monitor climate-related risks, including information about: [...]\n(ii) whether and how the entity uses climate-related scenario analysis to inform its identification of climate-related risks;",
    priority: 'moderate',
  },
    
  // --- Métricas e Metas ---
  {
    id: 'MM2.1',
    topic: 'Métricas e Metas',
    subtopic: 'Métricas de Desempenho',
    text: 'A entidade divulga as métricas que utiliza para medir e monitorar o desempenho de cada um de seus SRROs materiais?',
    type: 'boolean',
    evidence_prompt: 'Anexe a tabela ou lista que mapeia cada SRRO material à sua respectiva métrica de monitoramento.',
    reference: 'IFRS S1, §46',
    reference_text: "46 An entity shall disclose, for each sustainability-related risk and opportunity that could reasonably be expected to affect the entity's prospects:\n(a) metrics required by an applicable IFRS Sustainability Disclosure Standard; and\n(b) metrics the entity uses to measure and monitor:\n(i) that sustainability-related risk or opportunity; and\n(ii) its performance in relation to that sustainability-related risk or opportunity, including progress towards any targets the entity has set, and any targets it is required to meet by law or regulation.",
    priority: 'moderate',
  },
  {
    id: 'MM2.2',
    topic: 'Métricas e Metas',
    subtopic: 'Métricas de Desempenho',
    text: 'A entidade divulga as premissas e os processos utilizados para definir as métricas?',
    type: 'boolean',
    evidence_prompt: 'Para cada métrica, anexe a metodologia, as premissas e os processos de cálculo ou definição.',
    reference: 'IFRS S1, §50',
    reference_text: "50 If a metric has been developed by an entity, the entity shall disclose information about:\n(a) how the metric is defined, including whether it is derived by adjusting a metric taken from a source other than IFRS Sustainability Disclosure Standards and, if so, which source and how the metric disclosed by the entity differs from the metric specified in that source;\n(b) whether the metric is an absolute measure, a measure expressed in relation to another metric or a qualitative measure (such as a red, amber, green—or RAG—status);\n(c) whether the metric is validated by a third party and, if so, which party; and\n(d) the method used to calculate the metric and the inputs to the calculation, including the limitations of the method used and the significant assumptions made.",
    priority: 'moderate',
  },
  {
    id: 'MM2.3',
    topic: 'Métricas e Metas',
    subtopic: 'Métricas de Desempenho',
    text: 'Forneça a lista de métricas que a entidade utiliza para monitorar cada risco e oportunidade, incluindo a lista de indicadores climáticos.',
    type: 'text_block',
    evidence_prompt: 'Forneça a lista completa de métricas utilizadas para medir e monitorar o desempenho em relação a cada risco e oportunidade. Esta lista deve incluir os indicadores climáticos, tanto os de monitoramento contínuo quanto os atrelados a metas.',
    reference: 'IFRS S1.46, IFRS S2.27',
    reference_text: "IFRS S1, §46: An entity shall disclose, for each sustainability-related risk and opportunity that could reasonably be expected to affect the entity's prospects: (a) metrics required by an applicable IFRS Sustainability Disclosure Standard; and (b) metrics the entity uses to measure and monitor that sustainability-related risk or opportunity; and its performance in relation to that sustainability-related risk or opportunity, including progress towards any targets the entity has set, and any targets it is required to meet by law or regulation.\n---\nIFRS S2, §27: The objective of climate-related financial disclosures on metrics and targets is to enable users of general purpose financial reports to understand an entity's performance in relation to its climate-related risks and opportunities, including progress towards any climate-related targets it has set, and any targets it is required to meet by law or regulation.",
    priority: 'moderate',
  },
  {
    id: 'MM3.1',
    topic: 'Métricas e Metas',
    subtopic: 'Definição de Metas',
    text: 'A entidade divulga detalhes sobre as metas de sustentabilidade que estabeleceu?',
    type: 'text_block',
    evidence_prompt: 'Para cada meta, descreva a métrica utilizada, o período, o desempenho em relação à meta, e quaisquer marcos intermediários. Anexe a tabela de metas do relatório.',
    reference: 'IFRS S1, §51',
    reference_text: "51 An entity shall disclose information about the targets it has set to monitor progress towards achieving its strategic goals, and any targets it is required to meet by law or regulation. For each target, the entity shall disclose:\n(a) the metric used to set the target and to monitor progress towards reaching the target;\n(b) the specific quantitative or qualitative target the entity has set or is required to meet;\n(c) the period over which the target applies;\n(d) the base period from which progress is measured;\n(e) any milestones and interim targets;\n(f) performance against each target and an analysis of trends or changes in the entity's performance; and\n(g) any revisions to the target and an explanation for those revisions.",
    priority: 'moderate',
  },
  {
    id: 'MM3.2',
    topic: 'Métricas e Metas',
    subtopic: 'Definição de Metas',
    text: 'Descreva as métricas específicas usadas para definir e acompanhar o progresso em relação a cada meta climática que a entidade estabeleceu.',
    type: 'text_block',
    evidence_prompt: 'Descreva a métrica específica usada para cada meta climática. Exemplo: Para a meta "Reduzir emissões em 30%", a métrica é "% de redução de emissões GEE". Anexe a tabela de metas do relatório.',
    reference: 'IFRS S1.51(a), IFRS S2.33(a)',
    reference_text: "IFRS S1, §51(a): the metric used to set the target and to monitor progress towards reaching the target;\n---\nIFRS S2, §33: An entity shall disclose the quantitative and qualitative climate-related targets it has set to monitor progress towards achieving its strategic goals, and any targets it is required to meet by law or regulation, including any greenhouse gas emissions targets. For each target, the entity shall disclose:\n(a) the metric used to set the target (see paragraphs B66–B67);",
    priority: 'moderate',
  },
  {
    id: 'MM4.1',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'A entidade divulga suas emissões de GEE brutas absolutas para Escopo 1, 2 e 3?',
    type: 'boolean',
    evidence_prompt: 'Anexe o inventário de emissões de GEE ou a tabela correspondente do relatório.',
    reference: 'IFRS S2, §29(a)(i)',
    reference_text: "29(a) greenhouse gases—the entity shall:\n(i) disclose its absolute gross greenhouse gas emissions generated during the reporting period, expressed as metric tonnes of CO2 equivalent (see paragraphs B19-B22), classified as:\n(1) Scope 1 greenhouse gas emissions;\n(2) Scope 2 greenhouse gas emissions; and\n(3) Scope 3 greenhouse gas emissions;",
    priority: 'moderate',
  },
  {
    id: 'MM4.2',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'A entidade divulga a abordagem utilizada para medir suas emissões de GEE?',
    type: 'text',
    evidence_prompt: 'Descreva a abordagem de medição (ex: GHG Protocol), os inputs e as premissas utilizadas. Anexe a nota metodológica do inventário.',
    reference: 'IFRS S2, §29(a)(iii)',
    reference_text: "29(a)(iii) disclose the approach it uses to measure its greenhouse gas emissions (see paragraphs B26-B29) including:\n(1) the measurement approach, inputs and assumptions the entity uses to measure its greenhouse gas emissions;\n(2) the reason why the entity has chosen the measurement approach, inputs and assumptions it uses to measure its greenhouse gas emissions; and\n(3) any changes the entity made to the measurement approach, inputs and assumptions during the reporting period and the reasons for those changes;",
    priority: 'moderate',
  },
  {
    id: 'MM4.3',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'Detalhes do que está incluso nas Emissões GHG de Escopo 3.',
    type: 'text_block',
    evidence_prompt: 'Descreva em detalhes o que compõe as emissões de Escopo 3 reportadas. Anexe a memória de cálculo ou nota metodológica.',
    reference: 'IFRS S2.29(a)(vi)(1)',
    reference_text: "29(a)(vi) for Scope 3 greenhouse gas emissions disclosed in accordance with paragraph 29(a)(i)(3), and with reference to paragraphs B32-B57, disclose:\n(1) the categories included within the entity's measure of Scope 3 greenhouse gas emissions, in accordance with the Scope 3 categories described in the Greenhouse Gas Protocol Corporate Value Chain (Scope 3) Accounting and Reporting Standard (2011);",
    priority: 'moderate',
  },
  {
    id: 'MM4.4',
    topic: 'Métricas e Metas',
    subtopic: 'Emissões de GEE',
    text: 'Quais categorias estão inclusas na mensuração de Emissões GHG de Escopo 3?',
    type: 'multiple_choice',
    options: [
        'Categoria 1 - Bens e serviços adquiridos',
        'Categoria 2 - Bens de capital',
        'Categoria 3 - Atividades relacionadas a combustível e energia (não incluídas no Escopo 1 ou 2)',
        'Categoria 4 - Transporte e distribuição a montante',
        'Categoria 5 - Resíduos gerados nas operações',
        'Categoria 6 - Viagens de negócios',
        'Categoria 7 - Deslocamento de funcionários',
        'Categoria 8 - Ativos arrendados a montante',
        'Categoria 9 - Transporte e distribuição a jusante',
        'Categoria 10 - Processamento de produtos vendidos',
        'Categoria 11 - Uso de produtos vendidos',
        'Categoria 12 - Tratamento de fim de vida de produtos vendidos',
        'Categoria 13 - Ativos arrendados a jusante',
        'Categoria 14 - Franquias',
        'Categoria 15 - Investimentos',
    ],
    evidence_prompt: 'Selecione todas as categorias de Escopo 3 que são mensuradas e reportadas pela entidade. Anexe o inventário de GEE.',
    reference: 'IFRS S2.29(a)(vi)(1)',
    reference_text: "29(a)(vi) for Scope 3 greenhouse gas emissions disclosed in accordance with paragraph 29(a)(i)(3), and with reference to paragraphs B32-B57, disclose:\n(1) the categories included within the entity's measure of Scope 3 greenhouse gas emissions, in accordance with the Scope 3 categories described in the Greenhouse Gas Protocol Corporate Value Chain (Scope 3) Accounting and Reporting Standard (2011);",
    priority: 'moderate',
  },
  {
    id: 'MM5.1',
    topic: 'Métricas e Metas',
    subtopic: 'Exposição a Riscos Climáticos',
    text: 'A entidade divulga a exposição de seus ativos e atividades a riscos de transição climática?',
    type: 'text',
    evidence_prompt: 'Forneça o valor e a porcentagem de ativos ou atividades de negócio vulneráveis a riscos de transição. Anexe a análise de risco de transição.',
    reference: 'IFRS S2, §29(b)',
    reference_text: "29(b) climate-related transition risks—the amount and percentage of assets or business activities vulnerable to climate-related transition risks;",
    priority: 'moderate',
  },
  {
    id: 'MM5.2',
    topic: 'Métricas e Metas',
    subtopic: 'Exposição a Riscos Climáticos',
    text: 'A entidade divulga a exposição de seus ativos e atividades a riscos físicos climáticos?',
    type: 'text',
    evidence_prompt: 'Forneça o valor e a porcentagem de ativos ou atividades de negócio vulneráveis a riscos físicos. Anexe a análise de risco físico.',
    reference: 'IFRS S2, §29(c)',
    reference_text: "29(c) climate-related physical risks—the amount and percentage of assets or business activities vulnerable to climate-related physical risks;",
    priority: 'moderate',
  },
  {
    id: 'MM6.1',
    topic: 'Métricas e Metas',
    subtopic: 'Oportunidades e Investimento',
    text: 'A entidade divulga o alinhamento de seus ativos e atividades com oportunidades climáticas?',
    type: 'text',
    evidence_prompt: 'Forneça o valor e a porcentagem de ativos ou atividades de negócio alinhados com oportunidades relacionadas ao clima. Anexe o estudo de oportunidades.',
    reference: 'IFRS S2, §29(d)',
    reference_text: "29(d) climate-related opportunities—the amount and percentage of assets or business activities aligned with climate-related opportunities;",
    priority: 'moderate',
  },
  {
    id: 'MM6.2',
    topic: 'Métricas e Metas',
    subtopic: 'Oportunidades e Investimento',
    text: 'A entidade divulga o capital direcionado para riscos e oportunidades climáticas?',
    type: 'text',
    evidence_prompt: 'Forneça o montante de CAPEX, financiamento ou investimento direcionado para riscos e oportunidades climáticas. Anexe o plano de investimentos.',
    reference: 'IFRS S2, §29(e)',
    reference_text: "29(e) capital deployment—the amount of capital expenditure, financing or investment deployed towards climate-related risks and opportunities;",
    priority: 'moderate',
  },
  {
    id: 'MM7.1',
    topic: 'Métricas e Metas',
    subtopic: 'Precificação de Carbono',
    text: 'A entidade utiliza preços internos de carbono em suas decisões?',
    type: 'boolean',
    evidence_prompt: 'Se sim, explique como a precificação interna de carbono é usada e quais são os preços por tonelada de emissão de GEE. Anexe a política de precificação de carbono.',
    reference: 'IFRS S2, §29(f)',
    reference_text: "29(f) internal carbon prices—the entity shall disclose:\n(i) an explanation of whether and how the entity is applying a carbon price in decision-making (for example, investment decisions, transfer pricing and scenario analysis); and\n(ii) the price for each metric tonne of greenhouse gas emissions the entity uses to assess the costs of its greenhouse gas emissions;",
    priority: 'moderate',
  },
  {
    id: 'MM8.1',
    topic: 'Métricas e Metas',
    subtopic: 'Metas Climáticas',
    text: 'Detalhes das metas de emissões GHG.',
    type: 'text_block',
    evidence_prompt: 'Forneça detalhes sobre as metas de GEE, incluindo o ano base, o ano alvo, o percentual de redução e se é uma meta absoluta ou de intensidade.',
    reference: 'IFRS S2.36(d)',
    reference_text: "36 For each greenhouse gas emissions target disclosed in accordance with paragraphs 33-35, an entity shall disclose:\n(a) which greenhouse gases are covered by the target.\n(b) whether Scope 1, Scope 2 or Scope 3 greenhouse gas emissions are covered by the target.\n(c) whether the target is a gross greenhouse gas emissions target or net greenhouse gas emissions target. If the entity discloses a net greenhouse gas emissions target, the entity is also required to separately disclose its associated gross greenhouse gas emissions target (see paragraphs B68-B69).\n(d) whether the target was derived using a sectoral decarbonisation approach.\n(e) the entity's planned use of carbon credits to offset greenhouse gas emissions to achieve any net greenhouse gas emissions target. In explaining its planned use of carbon credits the entity shall disclose information including, and with reference to paragraphs B70-B71: [...]",
    priority: 'moderate',
  },
  {
    id: 'MM8.2',
    topic: 'Métricas e Metas',
    subtopic: 'Metas Climáticas',
    text: 'Gases de efeito estufa cobertos pela meta.',
    type: 'multiple_choice',
    options: [
      'Dióxido de carbono (CO2)',
      'Metano (CH4)',
      'Óxido nitroso (N2O)',
      'Hidrofluorcarbonetos (HFCs)',
      'Perfluorcarbonetos (PFCs)',
      'Hexafluoreto de enxofre (SF6)',
      'Trifluoreto de nitrogênio (NF3)',
    ],
    evidence_prompt: 'Selecione todos os gases cobertos pelas metas de GEE. Anexe a documentação da meta.',
    reference: 'IFRS S2.36(a)',
    reference_text: "36 For each greenhouse gas emissions target disclosed in accordance with paragraphs 33–35, an entity shall disclose:\n(a) which greenhouse gases are covered by the target.",
    priority: 'moderate',
  },
  {
    id: 'MM8.3',
    topic: 'Métricas e Metas',
    subtopic: 'Metas Climáticas',
    text: 'Quais escopos de emissões estão cobertos pelas metas?',
    type: 'multiple_choice',
    options: [
      'Escopo 1 (Emissões GHG)',
      'Escopo 2 (Emissões GHG)',
      'Escopo 3 (Emissões GHG)',
    ],
    evidence_prompt: 'Selecione todos os escopos de emissão cobertos pelas metas. Anexe a documentação da meta.',
    reference: 'IFRS S2.36(b)',
    reference_text: "36 For each greenhouse gas emissions target disclosed in accordance with paragraphs 33–35, an entity shall disclose:\n(b) whether Scope 1, Scope 2 or Scope 3 greenhouse gas emissions are covered by the target.",
    priority: 'moderate',
  },
  
  // --- Fontes de Orientação e Conformidade ---
  {
    id: 'FC1.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Processo de Materialidade',
    text: 'A organização divulga os temas materiais relacionados à sustentabilidade que possam impactar nos ativos da companhia?',
    type: 'boolean',
    evidence_prompt: 'Anexe a matriz de materialidade ou a seção do relatório que descreve os temas materiais identificados.',
    reference: 'IFRS S1, §17',
    reference_text: "17 An entity shall disclose material information about the sustainability-related risks and opportunities that could reasonably be expected to affect the entity's prospects.",
    priority: 'moderate',
  },
  {
    id: 'FC1.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Processo de Materialidade',
    text: 'Ao avaliar a materialidade, a entidade considera fatores quantitativos e qualitativos, bem como o impacto potencial de eventos futuros incertos sobre os fluxos de caixa?',
    type: 'boolean',
    evidence_prompt: 'Descreva como a entidade aplica fatores quantitativos e qualitativos na sua avaliação de materialidade e anexe a metodologia de materialidade.',
    reference: 'IFRS S1, Appendix B',
    reference_text: "B21 An entity shall assess whether the information identified in applying paragraph B20, either individually or in combination with other information, is material in the context of the entity's sustainability-related financial disclosures taken as a whole. In assessing whether information is material, an entity shall consider both quantitative and qualitative factors. For example, an entity might consider the magnitude and the nature of the effect of a sustainability-related risk or opportunity on the entity.\n---\nB22 In some cases, IFRS Sustainability Disclosure Standards require the disclosure of information about possible future events with uncertain outcomes. In judging whether information about such possible future events is material, an entity shall consider:\n(a) the potential effects of the events on the amount, timing and uncertainty of the entity's future cash flows over the short, medium and long term (referred to as 'the possible outcome'); and\n(b) the range of possible outcomes and the likelihood of the possible outcomes within that range.",
    priority: 'moderate',
  },
  {
    id: 'FC2.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Na ausência de normas IFRS que se apliquem a um SRRO, a entidade utiliza seu julgamento para identificar informações relevantes?',
    type: 'boolean',
    evidence_prompt: 'Descreva o processo de julgamento para identificar divulgações relevantes para SRROs não cobertos por normas específicas.',
    reference: 'IFRS S1, §57',
    reference_text: "57 In the absence of an IFRS Sustainability Disclosure Standard that specifically applies to a sustainability-related risk or opportunity, an entity shall apply judgement to identify information that:\n(a) is relevant to the decision-making of users of general purpose financial reports; and\n(b) faithfully represents that sustainability-related risk or opportunity.",
    priority: 'moderate',
  },
  {
    id: 'FC2.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Nesse julgamento, a entidade considera a aplicabilidade das métricas associadas aos tópicos inclusos no SASB Standards?',
    type: 'boolean',
    evidence_prompt: 'Especifique se e como as normas SASB foram consideradas e anexe a análise de aderência ao SASB.',
    reference: 'IFRS S1, §58(a)',
    reference_text: "58 In making the judgement described in paragraph 57:\n(a) an entity shall refer to and consider the applicability of the metrics associated with the disclosure topics included in the SASB Standards. An entity might conclude that the metrics specified in the SASB Standards are not applicable in the entity's circumstances.",
    priority: 'moderate',
  },
  {
    id: 'FC2.3',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Nesse julgamento, a entidade considera a aplicabilidade do CDSB Framework Application Guidance?',
    type: 'boolean',
    evidence_prompt: 'Especifique se e como o CDSB Framework foi considerado.',
    reference: 'IFRS S1, §58(b)(i)',
    reference_text: "58 In making the judgement described in paragraph 57:\n(b) an entity may—to the extent that these sources do not conflict with IFRS Sustainability Disclosure Standards—refer to and consider the applicability of:\n(i) the CDSB Framework Application Guidance;",
    priority: 'moderate',
  },
  {
    id: 'FC2.4',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Nesse julgamento, a entidade referencia e considera a aplicabilidade de outros órgãos padronizadores e informações de empresas do mesmo setor/região?',
    type: 'boolean',
    evidence_prompt: 'Especifique quais outras fontes foram consideradas (outros órgãos, relatórios de pares) e anexe o benchmark.',
    reference: 'IFRS S1, §58(b)(ii-iii)',
    reference_text: "58 In making the judgement described in paragraph 57:\n(b) an entity may—to the extent that these sources do not conflict with IFRS Sustainability Disclosure Standards—refer to and consider the applicability of:\n(ii) the most recent pronouncements of other standard-setting bodies whose requirements are designed to meet the information needs of users of general purpose financial reports; and\n(iii) the information, including metrics, disclosed by entities that operate in the same industry(s) or geographical region(s).",
    priority: 'moderate',
  },
  {
    id: 'FC3.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Fontes de Orientação',
    text: 'Os standards específicos, pronunciamentos, práticas e outras fontes de embasamento que a entidade utilizou são identificáveis?',
    type: 'text',
    evidence_prompt: 'Liste as normas, pronunciamentos (incluindo guias de indústria) e outras fontes de orientação que a entidade aplicou.',
    reference: 'IFRS S1, §59',
    reference_text: "59 An entity shall identify:\n(a) the specific standards, pronouncements, industry practice and other sources of guidance that the entity has applied in preparing its sustainability-related financial disclosures, including, if applicable, identifying the disclosure topics in the SASB Standards; and\n(b) the industry(s) specified in the IFRS Sustainability Disclosure Standards, the SASB Standards or other sources of guidance relating to a particular industry(s) that the entity has applied in preparing its sustainability-related financial disclosures, including in identifying applicable metrics.",
    priority: 'moderate',
  },
  {
    id: 'FC4.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'O período relatado no IFRS Sustainability Disclosure é o mesmo do Financial Disclosure?',
    type: 'boolean',
    evidence_prompt: 'Confirme as datas e os períodos de reporte para ambos os relatórios, indicando a página onde a informação se encontra.',
    reference: 'IFRS S1, §64',
    reference_text: "64 An entity shall report its sustainability-related financial disclosures at the same time as its related financial statements. The entity's sustainability- related financial disclosures shall cover the same reporting period as the related financial statements.",
    priority: 'moderate',
  },
  {
    id: 'FC4.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'Em caso de mudança no período de reporte, a entidade divulga o período compreendido e a motivação?',
    type: 'boolean',
    evidence_prompt: 'Anexe a justificativa da mudança do período de reporte.',
    reference: 'IFRS S1, §66',
    reference_text: "66 When an entity changes the end of its reporting period and provides sustainability-related financial disclosures for a period longer or shorter than 12 months, it shall disclose:\n(a) the period covered by the sustainability-related financial disclosures;\n(b) the reason for using a longer or shorter period; and\n(c) the fact that the amounts disclosed in the sustainability-related financial disclosures are not entirely comparable.",
    priority: 'moderate',
  },
  {
    id: 'FC5.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'A entidade divulga as informações de sustentabilidade como parte de seus relatórios financeiros de propósito geral?',
    type: 'single_choice',
    options: ['Relatório de Gestão', 'Relatório Anual Integrado', 'Outro Documento'],
    evidence_prompt: 'Especifique onde as divulgações de sustentabilidade podem ser encontradas e anexe o sumário do documento.',
    reference: 'IFRS S1, §60',
    reference_text: "60 An entity is required to provide disclosures required by IFRS Sustainability Disclosure Standards as part of its general purpose financial reports.",
    priority: 'moderate',
  },
  {
    id: 'FC5.2',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Estrutura do Relatório',
    text: 'Caso as informações sejam incluídas por referência cruzada a outros relatórios, essa referência torna a informação claramente identificável e acessível nas mesmas condições?',
    type: 'boolean',
    evidence_prompt: 'Anexe um exemplo de referência cruzada do relatório e descreva como a entidade garante clareza e acessibilidade.',
    reference: 'IFRS S1, §63',
    reference_text: "63 Information required by an IFRS Sustainability Disclosure Standard may be included in sustainability-related financial disclosures by cross-reference to another report published by the entity. If an entity includes information by cross-reference, the entity shall apply the requirements in paragraphs B45–B47.\n---\nB45 Information required by an IFRS Sustainability Disclosure Standard might be available in another report published by the entity. For example, the required information could be disclosed in the related financial statements. Material information can be included in an entity's sustainability-related financial disclosures by cross-reference, provided that:\n(a) the cross-referenced information is available on the same terms and at the same time as the sustainability-related financial disclosures; and\n(b) the complete set of sustainability-related financial disclosures is not made less understandable by including information by cross-reference.\n---\nB46 Information included by cross-reference becomes part of the complete set of sustainability-related financial disclosures and shall comply with the requirements of IFRS Sustainability Disclosure Standards. For example, it needs to be relevant, representationally faithful, comparable, verifiable, timely and understandable. The body(s) or individual(s) that authorises the general purpose financial reports takes the same responsibility for the information included by cross-reference as it does for the information included directly.\n---\nB47 If information required by an IFRS Sustainability Disclosure Standard is included by cross-reference:\n(a) the sustainability-related financial disclosures shall clearly identify the report within which that information is located and explain how to access that report; and\n(b) the cross-reference shall be to a precisely specified part of that report.",
    priority: 'moderate',
  },
  {
    id: 'FC6.1',
    topic: 'Fontes de Orientação e Conformidade',
    subtopic: 'Declaração de Conformidade',
    text: 'A entidade faz uma declaração explícita e sem reservas de conformidade com os IFRS Sustainability Disclosure Standards?',
    type: 'boolean',
    evidence_prompt: 'Anexe a declaração de conformidade exata, conforme publicada no relatório.',
    reference: 'IFRS S1, §72',
    reference_text: "72 An entity whose sustainability-related financial disclosures comply with all the requirements of IFRS Sustainability Disclosure Standards shall make an explicit and unreserved statement of compliance. An entity shall not describe sustainability-related financial disclosures as complying with IFRS Sustainability Disclosure Standards unless they comply with all the requirements of IFRS Sustainability Disclosure Standards.",
    priority: 'moderate',
  }
];